INSERT INTO "career_careerinfo" VALUES(1,'td','td','Perform engineering duties in designing, constructing, and testing aircraft, missiles, and spacecraft. May conduct basic and applied research to evaluate adaptability of materials and equipment to aircraft design and manufacture. May recommend improvements in testing equipment and techniques.',18);
INSERT INTO "career_careerinfo" VALUES(2,'job','job','Direct or coordinate activities of engineering or technical personnel involved in designing, fabricating, modifying, or testing of aircraft or aerospace products.',18);
INSERT INTO "career_careerinfo" VALUES(3,'job','job','Formulate conceptual design of aeronautical or aerospace products or systems to meet customer requirements.',18);
INSERT INTO "career_careerinfo" VALUES(4,'job','job','Plan or coordinate activities concerned with investigating and resolving customers'' reports of technical problems with aircraft or aerospace vehicles.',18);
INSERT INTO "career_careerinfo" VALUES(5,'kn','Engineering and Technology','product and service development',18);
INSERT INTO "career_careerinfo" VALUES(6,'kn','Engineering and Technology','design',18);
INSERT INTO "career_careerinfo" VALUES(7,'kn','Math and Science','physics',18);
INSERT INTO "career_careerinfo" VALUES(8,'kn','Math and Science','arithmetic, algebra, geometry, calculus, or statistics',18);
INSERT INTO "career_careerinfo" VALUES(9,'kn','Arts and Humanities','English language',18);
INSERT INTO "career_careerinfo" VALUES(10,'kn','Manufactured or Agricultural Goods','manufacture and distribution of products',18);
INSERT INTO "career_careerinfo" VALUES(11,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',18);
INSERT INTO "career_careerinfo" VALUES(12,'sk','Basic Skills','reading work related information',18);
INSERT INTO "career_careerinfo" VALUES(13,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',18);
INSERT INTO "career_careerinfo" VALUES(14,'sk','People and Technology Systems','thinking about the pros and cons of different options and picking the best one',18);
INSERT INTO "career_careerinfo" VALUES(15,'sk','People and Technology Systems','figuring out how a system should work and how changes in the future will affect it',18);
INSERT INTO "career_careerinfo" VALUES(16,'ab','Verbal','read and understand what is written',18);
INSERT INTO "career_careerinfo" VALUES(17,'ab','Verbal','communicate by speaking',18);
INSERT INTO "career_careerinfo" VALUES(18,'ab','Ideas and Logic','use rules to solve problems',18);
INSERT INTO "career_careerinfo" VALUES(19,'ab','Ideas and Logic','make general rules or come up with answers from lots of detailed information',18);
INSERT INTO "career_careerinfo" VALUES(20,'ab','Math','choose the right type of math to solve a problem',18);
INSERT INTO "career_careerinfo" VALUES(21,'ab','Math','add, subtract, multiply, or divide',18);
INSERT INTO "career_careerinfo" VALUES(22,'ab','Attention','pay attention to something without being distracted',18);
INSERT INTO "career_careerinfo" VALUES(23,'ps','ps','People interested in this work like activities that include ideas, thinking, and figuring things out.',18);
INSERT INTO "career_careerinfo" VALUES(24,'tech','Analytical or scientific software','The MathWorks MATLAB',18);
INSERT INTO "career_careerinfo" VALUES(25,'tech','Analytical or scientific software','Thermal Synthesizer System TSS',18);
INSERT INTO "career_careerinfo" VALUES(26,'tech','Development environment software','C',18);
INSERT INTO "career_careerinfo" VALUES(27,'tech','Development environment software','Digital Equipment Corporation DIGITAL Fortran 90',18);
INSERT INTO "career_careerinfo" VALUES(28,'tech','Computer aided design CAD software','Autodesk AutoCAD software',18);
INSERT INTO "career_careerinfo" VALUES(29,'tech','Computer aided design CAD software','Autodesk AutoCAD software',18);
INSERT INTO "career_careerinfo" VALUES(30,'tech','Computer aided design CAD software','Mathsoft Mathcad',18);
INSERT INTO "career_careerinfo" VALUES(31,'td','td','Assemble, fit, fasten, and install parts of airplanes, space vehicles, or missiles, such as tails, wings, fuselage, bulkheads, stabilizers, landing gear, rigging and control equipment, or heating and ventilating systems.',19);
INSERT INTO "career_careerinfo" VALUES(32,'job','job','Align and fit structural assemblies manually, or signal crane operators to position assemblies for joining.
',19);
INSERT INTO "career_careerinfo" VALUES(33,'job','job','Assemble prefabricated parts to form subassemblies.',19);
INSERT INTO "career_careerinfo" VALUES(34,'job','job','Assemble, install, and connect parts, fittings, and assemblies on aircraft, using layout tools, hand tools, power tools, and fasteners such as bolts, screws, rivets, and clamps.',19);
INSERT INTO "career_careerinfo" VALUES(35,'kn','Engineering and Technology','mechanical
',19);
INSERT INTO "career_careerinfo" VALUES(36,'kn','Arts and Humanities
','English language',19);
INSERT INTO "career_careerinfo" VALUES(37,'sk','Basic Skills','figuring out how to use new ideas or things',19);
INSERT INTO "career_careerinfo" VALUES(38,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',19);
INSERT INTO "career_careerinfo" VALUES(39,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',19);
INSERT INTO "career_careerinfo" VALUES(40,'ab','Hand and Finger Use','hold or move items with your hands',19);
INSERT INTO "career_careerinfo" VALUES(41,'ab','Hand and Finger Use','put together small parts with your fingers',19);
INSERT INTO "career_careerinfo" VALUES(42,'ab','Ideas and Logic','notice when problems happen',19);
INSERT INTO "career_careerinfo" VALUES(43,'ab','Ideas and Logic','order or arrange things',19);
INSERT INTO "career_careerinfo" VALUES(44,'ps','ps','People interested in this work like activities that include practical, hands-on problems and solutions.',19);
INSERT INTO "career_careerinfo" VALUES(45,'td','td','Plan, direct, or coordinate activities in such fields as architecture and engineering or research and development in these fields.',20);
INSERT INTO "career_careerinfo" VALUES(46,'job','job','Manage the coordination and overall integration of technical activities in architecture or engineering projects.',20);
INSERT INTO "career_careerinfo" VALUES(47,'job','job','Direct, review, or approve project design changes.',20);
INSERT INTO "career_careerinfo" VALUES(48,'job','job','Confer with management, production, or marketing staff to discuss project specifications or procedures.',20);
INSERT INTO "career_careerinfo" VALUES(49,'kn','Engineering and Technology','product and service development',20);
INSERT INTO "career_careerinfo" VALUES(50,'kn','Engineering and Technology','design',20);
INSERT INTO "career_careerinfo" VALUES(51,'kn','Math and Science','arithmetic, algebra, geometry, calculus, or statistics',20);
INSERT INTO "career_careerinfo" VALUES(52,'kn','Math and Science','physics',20);
INSERT INTO "career_careerinfo" VALUES(53,'kn','Business','management',20);
INSERT INTO "career_careerinfo" VALUES(54,'kn','Business','customer service',20);
INSERT INTO "career_careerinfo" VALUES(55,'kn','Arts and Humanities','English language',20);
INSERT INTO "career_careerinfo" VALUES(56,'sk','Basic Skills','reading work related information',20);
INSERT INTO "career_careerinfo" VALUES(57,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',20);
INSERT INTO "career_careerinfo" VALUES(58,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',20);
INSERT INTO "career_careerinfo" VALUES(59,'sk','People and Technology Systems','thinking about the pros and cons of different options and picking the best one',20);
INSERT INTO "career_careerinfo" VALUES(60,'sk','People and Technology Systems','figuring out how a system should work and how changes in the future will affect it',20);
INSERT INTO "career_careerinfo" VALUES(61,'ab','Verbal','read and understand what is written',20);
INSERT INTO "career_careerinfo" VALUES(62,'ab','Verbal','communicate by speaking',20);
INSERT INTO "career_careerinfo" VALUES(63,'ab','Ideas and Logic','make general rules or come up with answers from lots of detailed information',20);
INSERT INTO "career_careerinfo" VALUES(64,'ab','Ideas and Logic','notice when problems happen',20);
INSERT INTO "career_careerinfo" VALUES(65,'ab','Math','choose the right type of math to solve a problem',20);
INSERT INTO "career_careerinfo" VALUES(66,'ab','Math','add, subtract, multiply, or divide',20);
INSERT INTO "career_careerinfo" VALUES(67,'ps','ps','People interested in this work like activities that include leading, making decisions, and business.',20);
INSERT INTO "career_careerinfo" VALUES(69,'tech','Computer aided design CAD software','Autodesk AutoCAD software
',20);
INSERT INTO "career_careerinfo" VALUES(70,'tech','Computer aided design CAD software','Hewlett-Packard HP SolidDesigner',20);
INSERT INTO "career_careerinfo" VALUES(71,'tech','Project management software','Microsoft Project',20);
INSERT INTO "career_careerinfo" VALUES(72,'tech','Project management software','Realization Streamliner',20);
INSERT INTO "career_careerinfo" VALUES(73,'tech','Analytical or scientific software','HEC RAS',20);
INSERT INTO "career_careerinfo" VALUES(74,'tech','Analytical or scientific software','HEC-1',20);
INSERT INTO "career_careerinfo" VALUES(75,'td','td','Design chemical plant equipment and devise processes for manufacturing chemicals and products, such as gasoline, synthetic rubber, plastics, detergents, cement, paper, and pulp, by applying principles and technology of chemistry, physics, and engineering.',22);
INSERT INTO "career_careerinfo" VALUES(76,'job','job','Develop safety procedures to be employed by workers operating equipment or working in close proximity to on-going chemical reactions.',22);
INSERT INTO "career_careerinfo" VALUES(77,'job','job','Troubleshoot problems with chemical manufacturing processes.',22);
INSERT INTO "career_careerinfo" VALUES(78,'job','job','Evaluate chemical equipment and processes to identify ways to optimize performance or to ensure compliance with safety and environmental regulations.',22);
INSERT INTO "career_careerinfo" VALUES(79,'kn','Engineering and Technology','product and service development',22);
INSERT INTO "career_careerinfo" VALUES(80,'kn','Engineering and Technology','design',22);
INSERT INTO "career_careerinfo" VALUES(81,'kn','Math and Science','chemistry',22);
INSERT INTO "career_careerinfo" VALUES(82,'kn','Math and Science','arithmetic, algebra, geometry, calculus, or statistics',22);
INSERT INTO "career_careerinfo" VALUES(83,'kn','Manufactured or Agricultural Goods','manufacture and distribution of products',22);
INSERT INTO "career_careerinfo" VALUES(84,'kn','Arts and Humanities','English language',22);
INSERT INTO "career_careerinfo" VALUES(85,'sk','Basic Skills','using scientific rules and strategies to solve problems',22);
INSERT INTO "career_careerinfo" VALUES(86,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',22);
INSERT INTO "career_careerinfo" VALUES(87,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',22);
INSERT INTO "career_careerinfo" VALUES(88,'sk','People and Technology Systems','figuring out how a system should work and how changes in the future will affect it',22);
INSERT INTO "career_careerinfo" VALUES(89,'sk','People and Technology Systems','thinking about the pros and cons of different options and picking the best one',22);
INSERT INTO "career_careerinfo" VALUES(90,'ac','ac','Chemical Engineer, Engineer, Process Engineer, Scientist',22);
INSERT INTO "career_careerinfo" VALUES(91,'ab','Ideas and Logic','notice when problems happen',22);
INSERT INTO "career_careerinfo" VALUES(92,'ab','Ideas and Logic','order or arrange things',22);
INSERT INTO "career_careerinfo" VALUES(93,'ab','Math','choose the right type of math to solve a problem',22);
INSERT INTO "career_careerinfo" VALUES(94,'ab','Math','add, subtract, multiply, or divide',22);
INSERT INTO "career_careerinfo" VALUES(95,'ab','Verbal','listen and understand what people say',22);
INSERT INTO "career_careerinfo" VALUES(96,'ab','Verbal','read and understand what is written',22);
INSERT INTO "career_careerinfo" VALUES(97,'ab','Visual Understanding','see hidden patterns',22);
INSERT INTO "career_careerinfo" VALUES(98,'ps','ps','People interested in this work like activities that include ideas, thinking, and figuring things out.',22);
INSERT INTO "career_careerinfo" VALUES(99,'tech','Analytical or scientific software','Chempute Software Engineer''s Aide SINET',22);
INSERT INTO "career_careerinfo" VALUES(100,'tech','Analytical or scientific software','G&P Engineering Software EngVert',22);
INSERT INTO "career_careerinfo" VALUES(101,'tech','Data base user interface and query software','Chempute Software E-Notebook',22);
INSERT INTO "career_careerinfo" VALUES(102,'tech','Data base user interface and query software','G&P Engineering Software PhysProps',22);
INSERT INTO "career_careerinfo" VALUES(103,'tech','Spreadsheet software','Microsoft Excel',22);
INSERT INTO "career_careerinfo" VALUES(104,'ac','ac','Bridge/Structure Inspection Team Leader, County Engineer, Railroad Design Consultant, Structural Engineer',23);
INSERT INTO "career_careerinfo" VALUES(105,'td','td','Perform engineering duties in planning, designing, and overseeing construction and maintenance of building structures, and facilities, such as roads, railroads, airports, bridges, harbors, channels, dams, irrigation projects, pipelines, power plants, and water and sewage systems.',23);
INSERT INTO "career_careerinfo" VALUES(106,'job','job','Inspect project sites to monitor progress and ensure conformance to design specifications and safety or sanitation standards.',23);
INSERT INTO "career_careerinfo" VALUES(107,'job','job','Compute load and grade requirements, water flow rates, or material stress factors to determine design specifications.',23);
INSERT INTO "career_careerinfo" VALUES(108,'job','job','Provide technical advice to industrial or managerial personnel regarding design, construction, or program modifications or structural repairs.',23);
INSERT INTO "career_careerinfo" VALUES(109,'kn','Engineering and Technology','product and service development',23);
INSERT INTO "career_careerinfo" VALUES(110,'kn','Engineering and Technology','building and construction',23);
INSERT INTO "career_careerinfo" VALUES(111,'kn','Math and Science','arithmetic, algebra, geometry, calculus, or statistics',23);
INSERT INTO "career_careerinfo" VALUES(112,'kn','Math and Science','physics',23);
INSERT INTO "career_careerinfo" VALUES(113,'kn','Arts and Humanities','English language',23);
INSERT INTO "career_careerinfo" VALUES(114,'kn','Business','management',23);
INSERT INTO "career_careerinfo" VALUES(115,'sk','Basic Skills','reading work related information',23);
INSERT INTO "career_careerinfo" VALUES(116,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',23);
INSERT INTO "career_careerinfo" VALUES(117,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',23);
INSERT INTO "career_careerinfo" VALUES(118,'sk','People and Technology Systems','figuring out how a system should work and how changes in the future will affect it',23);
INSERT INTO "career_careerinfo" VALUES(119,'sk','People and Technology Systems','measuring how well a system is working and how to improve it',23);
INSERT INTO "career_careerinfo" VALUES(120,'ab','Verbal','communicate by speaking',23);
INSERT INTO "career_careerinfo" VALUES(121,'ab','Verbal','listen and understand what people say',23);
INSERT INTO "career_careerinfo" VALUES(122,'ab','Ideas and Logic','make general rules or come up with answers from lots of detailed information',23);
INSERT INTO "career_careerinfo" VALUES(123,'ab','Ideas and Logic','notice when problems happen',23);
INSERT INTO "career_careerinfo" VALUES(124,'ab','Math','choose the right type of math to solve a problem',23);
INSERT INTO "career_careerinfo" VALUES(125,'ab','Math','add, subtract, multiply, or divide',23);
INSERT INTO "career_careerinfo" VALUES(126,'ab','Visual Understanding','see hidden patterns',23);
INSERT INTO "career_careerinfo" VALUES(127,'ps','ps','People interested in this work like activities that include practical, hands-on problems and solutions.',23);
INSERT INTO "career_careerinfo" VALUES(128,'tech','Computer aided design CAD software','Autodesk AutoCAD software',23);
INSERT INTO "career_careerinfo" VALUES(129,'tech','Computer aided design CAD software','Bentley MicroStation',23);
INSERT INTO "career_careerinfo" VALUES(130,'tech','Analytical or scientific software','HEC-1',23);
INSERT INTO "career_careerinfo" VALUES(131,'tech','Analytical or scientific software','Hydraulic modeling software',23);
INSERT INTO "career_careerinfo" VALUES(132,'tech','Map creation software','Cartography software',23);
INSERT INTO "career_careerinfo" VALUES(133,'tech','Map creation software','ESRI ArcView',23);
INSERT INTO "career_careerinfo" VALUES(134,'ac','ac','Application Integration Engineer, Programmer Analyst, Software Development Engineer, Software Engineer',24);
INSERT INTO "career_careerinfo" VALUES(135,'td','td','Develop, create, and modify general computer applications software or specialized utility programs. Analyze user needs and develop software solutions. Design software or customize software for client use with the aim of optimizing operational efficiency. May analyze and design databases within an application area, working individually or coordinating database development as part of a team. May supervise computer programmers.',24);
INSERT INTO "career_careerinfo" VALUES(136,'job','job','Modify existing software to correct errors, allow it to adapt to new hardware, or to improve its performance.',24);
INSERT INTO "career_careerinfo" VALUES(137,'job','job','Develop and direct software system testing and validation procedures, programming, and documentation.',24);
INSERT INTO "career_careerinfo" VALUES(138,'job','job','Confer with systems analysts, engineers, programmers and others to design system and to obtain information on project limitations and capabilities, performance requirements and interfaces.',24);
INSERT INTO "career_careerinfo" VALUES(139,'kn','Engineering and Technology','computers and electronics',24);
INSERT INTO "career_careerinfo" VALUES(140,'kn','Engineering and Technology','product and service development',24);
INSERT INTO "career_careerinfo" VALUES(141,'kn','Math and Science','arithmetic, algebra, geometry, calculus, or statistics',24);
INSERT INTO "career_careerinfo" VALUES(142,'kn','Arts and Humanities','English language',24);
INSERT INTO "career_careerinfo" VALUES(143,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',24);
INSERT INTO "career_careerinfo" VALUES(144,'sk','Basic Skills','listening to others, not interrupting, and asking good questions',24);
INSERT INTO "career_careerinfo" VALUES(145,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',24);
INSERT INTO "career_careerinfo" VALUES(146,'sk','People and Technology Systems','figuring out how a system should work and how changes in the future will affect it',24);
INSERT INTO "career_careerinfo" VALUES(147,'sk','People and Technology Systems','measuring how well a system is working and how to improve it',24);
INSERT INTO "career_careerinfo" VALUES(148,'ab','Ideas and Logic','notice when problems happen',24);
INSERT INTO "career_careerinfo" VALUES(149,'ab','Ideas and Logic','use rules to solve problems',24);
INSERT INTO "career_careerinfo" VALUES(150,'ab','Math','choose the right type of math to solve a problem',24);
INSERT INTO "career_careerinfo" VALUES(151,'ab','Math','add, subtract, multiply, or divide',24);
INSERT INTO "career_careerinfo" VALUES(152,'ab','Verbal','communicate by speaking',24);
INSERT INTO "career_careerinfo" VALUES(153,'ab','Verbal','listen and understand what people say',24);
INSERT INTO "career_careerinfo" VALUES(154,'ps','ps','People interested in this work like activities that include ideas, thinking, and figuring things out.',24);
INSERT INTO "career_careerinfo" VALUES(155,'tech','Development environment software','C',24);
INSERT INTO "career_careerinfo" VALUES(156,'tech','Development environment software','IBM Rational Rose XDE Developer',24);
INSERT INTO "career_careerinfo" VALUES(157,'tech','Object or component oriented development software','C++',24);
INSERT INTO "career_careerinfo" VALUES(158,'tech','Object or component oriented development software','Python',24);
INSERT INTO "career_careerinfo" VALUES(159,'tech','Program testing software','Defect tracking software',24);
INSERT INTO "career_careerinfo" VALUES(160,'tech','Program testing software','Mercury Interactive LoadRunner',24);
INSERT INTO "career_careerinfo" VALUES(161,'ac','ac','Accountant, Accounting Manager, Certified Public Accountant (CPA), Staff Accountant',63);
INSERT INTO "career_careerinfo" VALUES(162,'td','td','Analyze financial information and prepare financial reports to determine or maintain record of assets, liabilities, profit and loss, tax liability, or other financial activities within an organization.',63);
INSERT INTO "career_careerinfo" VALUES(163,'job','job','Prepare, examine, or analyze accounting records, financial statements, or other financial reports to assess accuracy, completeness, and conformance to reporting and procedural standards.',63);
INSERT INTO "career_careerinfo" VALUES(164,'job','job','Report to management regarding the finances of establishment.',63);
INSERT INTO "career_careerinfo" VALUES(165,'job','job','Establish tables of accounts and assign entries to proper accounts.',63);
INSERT INTO "career_careerinfo" VALUES(166,'kn','Business','accounting and economics',63);
INSERT INTO "career_careerinfo" VALUES(167,'kn','Business','administrative services',63);
INSERT INTO "career_careerinfo" VALUES(168,'kn','Math and Science','arithmetic, algebra, geometry, calculus, or statistics',63);
INSERT INTO "career_careerinfo" VALUES(169,'kn','Arts and Humanities
','English language',63);
INSERT INTO "career_careerinfo" VALUES(170,'kn','Engineering and Technology
','computers and electronics',63);
INSERT INTO "career_careerinfo" VALUES(171,'sk','Basic Skills
','listening to others, not interrupting, and asking good questions',63);
INSERT INTO "career_careerinfo" VALUES(172,'sk','Basic Skills','using math to solve problems',63);
INSERT INTO "career_careerinfo" VALUES(173,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',63);
INSERT INTO "career_careerinfo" VALUES(174,'sk','People and Technology Systems
','thinking about the pros and cons of different options and picking the best one',63);
INSERT INTO "career_careerinfo" VALUES(175,'sk','People and Technology Systems','figuring out how a system should work and how changes in the future will affect it',63);
INSERT INTO "career_careerinfo" VALUES(176,'ab','Math
','choose the right type of math to solve a problem',63);
INSERT INTO "career_careerinfo" VALUES(177,'ab','Math','add, subtract, multiply, or divide',63);
INSERT INTO "career_careerinfo" VALUES(178,'ab','Verbal
','listen and understand what people say',63);
INSERT INTO "career_careerinfo" VALUES(179,'ab','Verbal','read and understand what is written',63);
INSERT INTO "career_careerinfo" VALUES(180,'ab','Ideas and Logic
','use rules to solve problems',63);
INSERT INTO "career_careerinfo" VALUES(181,'ab','Ideas and Logic','make general rules or come up with answers from lots of detailed information',63);
INSERT INTO "career_careerinfo" VALUES(182,'ab','Attention
','pay attention to something without being distracted',63);
INSERT INTO "career_careerinfo" VALUES(183,'ps','ps','People interested in this work like activities that include data, detail, and regular routines.',63);
INSERT INTO "career_careerinfo" VALUES(184,'tech','Accounting software
','ATX Total Accounting Office',63);
INSERT INTO "career_careerinfo" VALUES(185,'tech','Accounting software','Intuit QuickBooks software',63);
INSERT INTO "career_careerinfo" VALUES(186,'tech','Tax preparation software
','ATX Total Tax Office',63);
INSERT INTO "career_careerinfo" VALUES(187,'tech','Tax preparation software','CCH ProSystem fx TAX',63);
INSERT INTO "career_careerinfo" VALUES(188,'tech','Financial analysis software
','Brentmark Estate Planning Quickview',63);
INSERT INTO "career_careerinfo" VALUES(189,'tech','Financial analysis software','Cartesis Magnitude iAnalysis',63);
INSERT INTO "career_careerinfo" VALUES(190,'ac','ac','Administrative Assistant, Administrative Secretary, Office Assistant, Secretary',68);
INSERT INTO "career_careerinfo" VALUES(191,'td','td','Perform routine clerical and administrative functions such as drafting correspondence, scheduling appointments, organizing and maintaining paper and electronic files, or providing information to callers.',68);
INSERT INTO "career_careerinfo" VALUES(192,'job','job','Use computers for various applications, such as database management or word processing.',68);
INSERT INTO "career_careerinfo" VALUES(193,'job','job','Answer telephones and give information to callers, take messages, or transfer calls to appropriate individuals.',68);
INSERT INTO "career_careerinfo" VALUES(194,'job','job','Create, maintain, and enter information into databases.',68);
INSERT INTO "career_careerinfo" VALUES(195,'kn','Business
','administrative services',68);
INSERT INTO "career_careerinfo" VALUES(196,'kn','Business
','customer service',68);
INSERT INTO "career_careerinfo" VALUES(197,'kn','Arts and Humanities
','English language',68);
INSERT INTO "career_careerinfo" VALUES(198,'kn','Engineering and Technology
','computers and electronics',68);
INSERT INTO "career_careerinfo" VALUES(199,'sk','Basic Skills
','writing things for co-workers or customers',68);
INSERT INTO "career_careerinfo" VALUES(200,'sk','Basic Skills
','listening to others, not interrupting, and asking good questions
',68);
INSERT INTO "career_careerinfo" VALUES(201,'sk','Social
','looking for ways to help people',68);
INSERT INTO "career_careerinfo" VALUES(202,'sk','Social','changing what is done based on other people''s actions',68);
INSERT INTO "career_careerinfo" VALUES(203,'ab','Verbal
','listen and understand what people say',68);
INSERT INTO "career_careerinfo" VALUES(204,'ab','Verbal','communicate by speaking',68);
INSERT INTO "career_careerinfo" VALUES(205,'ab','Ideas and Logic
','order or arrange things',68);
INSERT INTO "career_careerinfo" VALUES(206,'ab','Ideas and Logic','notice when problems happen',68);
INSERT INTO "career_careerinfo" VALUES(207,'ps','ps','People interested in this work like activities that include data, detail, and regular routines.',68);
INSERT INTO "career_careerinfo" VALUES(208,'tech','Data base user interface and query software
','Database software',68);
INSERT INTO "career_careerinfo" VALUES(209,'tech','Data base user interface and query software','Microsoft Access',68);
INSERT INTO "career_careerinfo" VALUES(210,'tech','Electronic mail software
','Email software',68);
INSERT INTO "career_careerinfo" VALUES(211,'tech','Electronic mail software','Microsoft Outlook',68);
INSERT INTO "career_careerinfo" VALUES(212,'tech','Accounting software
','IBM Maximo Asset Management',68);
INSERT INTO "career_careerinfo" VALUES(213,'tech','Accounting software','Intuit QuickBooks software',68);
INSERT INTO "career_careerinfo" VALUES(214,'td','td','Buy and sell securities and commodities to transfer debt, capital, or risk. Establish and negotiate unit prices and terms of sale.',69);
INSERT INTO "career_careerinfo" VALUES(215,'job','job','Agree on buying or selling prices at optimal levels for clients.',69);
INSERT INTO "career_careerinfo" VALUES(216,'job ','job','Analyze target companies or investment opportunities to inform investment decisions.',69);
INSERT INTO "career_careerinfo" VALUES(217,'job','job','Buy or sell stocks, bonds, commodity futures, foreign currencies, or other securities on behalf of investment dealers.',69);
INSERT INTO "career_careerinfo" VALUES(218,'kn','kn','Knowledge information for this career will be available soon.',69);
INSERT INTO "career_careerinfo" VALUES(219,'sk','sk','Knowledge information for this career will be available soon.',69);
INSERT INTO "career_careerinfo" VALUES(220,'ab','ab','Knowledge information for this career will be available soon.',69);
INSERT INTO "career_careerinfo" VALUES(221,'ps','ps','People interested in this work like activities that include leading, making decisions, and business.',69);
INSERT INTO "career_careerinfo" VALUES(222,'tech','Financial analysis software
','Bloomberg Professional',69);
INSERT INTO "career_careerinfo" VALUES(223,'tech','Financial analysis software','BondDesk Group Trader WorkStation',69);
INSERT INTO "career_careerinfo" VALUES(224,'tech','Object or component oriented development software','C++',69);
INSERT INTO "career_careerinfo" VALUES(225,'tech','Object or component oriented development software','R',69);
INSERT INTO "career_careerinfo" VALUES(226,'tech','Spreadsheet software
','Microsoft Excel',69);
INSERT INTO "career_careerinfo" VALUES(227,'ac','ac','Actuarial Analyst, Actuary, Pricing Actuary, Product Development Actuary',71);
INSERT INTO "career_careerinfo" VALUES(228,'td','td','Analyze statistical data, such as mortality, accident, sickness, disability, and retirement rates and construct probability tables to forecast risk and liability for payment of future benefits. May ascertain insurance rates required and cash reserves necessary to ensure payment of future benefits.
',71);
INSERT INTO "career_careerinfo" VALUES(229,'job','job','Ascertain premium rates required and cash reserves and liabilities necessary to ensure payment of future benefits.',71);
INSERT INTO "career_careerinfo" VALUES(230,'job','job','Determine or help determine company policy, and explain complex technical matters to company executives, government officials, shareholders, policyholders, or the public.',71);
INSERT INTO "career_careerinfo" VALUES(231,'job','job','Design, review and help administer insurance, annuity and pension plans, determining financial soundness and calculating premiums.
',71);
INSERT INTO "career_careerinfo" VALUES(232,'kn','Math and Science','arithmetic, algebra, geometry, calculus, or statistics',71);
INSERT INTO "career_careerinfo" VALUES(233,'kn','Business','accounting and economics',71);
INSERT INTO "career_careerinfo" VALUES(234,'kn','Business','management',71);
INSERT INTO "career_careerinfo" VALUES(235,'kn','Arts and Humanities','English language',71);
INSERT INTO "career_careerinfo" VALUES(236,'kn','Engineering and Technology
','computers and electronics',71);
INSERT INTO "career_careerinfo" VALUES(237,'sk','Basic Skills','using math to solve problems',71);
INSERT INTO "career_careerinfo" VALUES(238,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',71);
INSERT INTO "career_careerinfo" VALUES(239,'sk','People and Technology Systems','thinking about the pros and cons of different options and picking the best one',71);
INSERT INTO "career_careerinfo" VALUES(240,'sk','People and Technology Systems','figuring out how a system should work and how changes in the future will affect it',71);
INSERT INTO "career_careerinfo" VALUES(241,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',71);
INSERT INTO "career_careerinfo" VALUES(242,'ab','Math','choose the right type of math to solve a problem',71);
INSERT INTO "career_careerinfo" VALUES(243,'sk','Math','add, subtract, multiply, or divide',71);
INSERT INTO "career_careerinfo" VALUES(244,'ab','Verbal','communicate by speaking',71);
INSERT INTO "career_careerinfo" VALUES(245,'ab','Verbal','read and understand what is written',71);
INSERT INTO "career_careerinfo" VALUES(246,'ab','Ideas and Logic','use rules to solve problems',71);
INSERT INTO "career_careerinfo" VALUES(247,'ab','Ideas and Logic','make general rules or come up with answers from lots of detailed information',71);
INSERT INTO "career_careerinfo" VALUES(248,'ab','Attention','pay attention to something without being distracted',71);
INSERT INTO "career_careerinfo" VALUES(249,'ps','ps','People interested in this work like activities that include data, detail, and regular routines.',71);
INSERT INTO "career_careerinfo" VALUES(250,'tech','Financial analysis software','GGY AXIS',71);
INSERT INTO "career_careerinfo" VALUES(251,'tech','Financial analysis software','PolySystems Asset Delphi',71);
INSERT INTO "career_careerinfo" VALUES(252,'tech','Analytical or scientific software','Insightful S-PLUS',71);
INSERT INTO "career_careerinfo" VALUES(253,'tech','Analytical or scientific software','SAS software',71);
INSERT INTO "career_careerinfo" VALUES(254,'tech','Data base user interface and query software','dBASE Plus',71);
INSERT INTO "career_careerinfo" VALUES(255,'tech','Data base user interface and query software','SAP BusinessObjects Desktop Intelligence',71);
INSERT INTO "career_careerinfo" VALUES(256,'ac','ac','Dental Science',54);
INSERT INTO "career_careerinfo" VALUES(257,'td','td','Examine, diagnose, and treat diseases, injuries, and malformations of teeth and gums. May treat diseases of nerve, pulp, and other dental tissues affecting oral hygiene and retention of teeth. May fit dental appliances or provide preventive care.',54);
INSERT INTO "career_careerinfo" VALUES(258,'job','job','Use masks, gloves, and safety glasses to protect patients and self from infectious diseases.',54);
INSERT INTO "career_careerinfo" VALUES(259,'job','job','Examine teeth, gums, and related tissues, using dental instruments, x-rays, or other diagnostic equipment, to evaluate dental health, diagnose diseases or abnormalities, and plan appropriate treatments.',54);
INSERT INTO "career_careerinfo" VALUES(260,'job','job','Administer anesthetics to limit the amount of pain experienced by patients during procedures.',54);
INSERT INTO "career_careerinfo" VALUES(261,'kn','Health','medicine and dentistry',54);
INSERT INTO "career_careerinfo" VALUES(262,'kn','Business
','customer service',54);
INSERT INTO "career_careerinfo" VALUES(263,'kn','Business','management',54);
INSERT INTO "career_careerinfo" VALUES(264,'kn','Business','management',54);
INSERT INTO "career_careerinfo" VALUES(265,'kn','Arts and Humanities','English language',54);
INSERT INTO "career_careerinfo" VALUES(266,'kn','Math and Science','biology',54);
INSERT INTO "career_careerinfo" VALUES(267,'sk','Basic Skills','thinking about the pros and cons of different ways to solve a problem',54);
INSERT INTO "career_careerinfo" VALUES(268,'sk','Basic Skills','keeping track of how well people and/or groups are doing in order to make improvements',54);
INSERT INTO "career_careerinfo" VALUES(269,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',54);
INSERT INTO "career_careerinfo" VALUES(270,'sk','Social','looking for ways to help people',54);
INSERT INTO "career_careerinfo" VALUES(271,'sk','Social','understanding people''s reactions',54);
INSERT INTO "career_careerinfo" VALUES(272,'ab','Hand and Finger Use','put together small parts with your fingers',54);
INSERT INTO "career_careerinfo" VALUES(273,'ab','Hand and Finger Use','keep your arm or hand steady',54);
INSERT INTO "career_careerinfo" VALUES(274,'ab','Verbal','communicate by speaking',54);
INSERT INTO "career_careerinfo" VALUES(275,'ab','Verbal','listen and understand what people say',54);
INSERT INTO "career_careerinfo" VALUES(276,'ab','Ideas and Logic','notice when problems happen',54);
INSERT INTO "career_careerinfo" VALUES(277,'ab','Ideas and Logic','make general rules or come up with answers from lots of detailed information',54);
INSERT INTO "career_careerinfo" VALUES(278,'ab','Attention','pay attention to something without being distracted',54);
INSERT INTO "career_careerinfo" VALUES(279,'ps','ps','People interested in this work like activities that include ideas, thinking, and figuring things out.',54);
INSERT INTO "career_careerinfo" VALUES(280,'tech','Medical software','AlphaDent',54);
INSERT INTO "career_careerinfo" VALUES(281,'tech','Medical software','DentiMax',54);
INSERT INTO "career_careerinfo" VALUES(282,'tech','Spreadsheet software','',54);
INSERT INTO "career_careerinfo" VALUES(283,'tech','Accounting software','',54);
INSERT INTO "career_careerinfo" VALUES(284,'ac','ac','Clinical Dietitian, Dietitian, Nutritionist, Registered Dietitian',55);
INSERT INTO "career_careerinfo" VALUES(285,'td','td','Plan and conduct food service or nutritional programs to assist in the promotion of health and control of disease. May supervise activities of a department providing quantity food services, counsel individuals, or conduct nutritional research.',55);
INSERT INTO "career_careerinfo" VALUES(286,'job','job','Monitor food service operations to ensure conformance to nutritional, safety, sanitation and quality standards.',55);
INSERT INTO "career_careerinfo" VALUES(287,'job','job','Assess nutritional needs, diet restrictions and current health plans to develop and implement dietary-care plans and provide nutritional counseling.',55);
INSERT INTO "career_careerinfo" VALUES(288,'job','job','Advise patients and their families on nutritional principles, dietary plans and diet modifications, and food selection and preparation.',55);
INSERT INTO "career_careerinfo" VALUES(289,'kn','Business','customer service',55);
INSERT INTO "career_careerinfo" VALUES(290,'kn','Business','management',55);
INSERT INTO "career_careerinfo" VALUES(291,'kn','Education and Training','teaching and course design',55);
INSERT INTO "career_careerinfo" VALUES(292,'kn','Arts and Humanities','English language',55);
INSERT INTO "career_careerinfo" VALUES(293,'kn','Math and Science','biology',55);
INSERT INTO "career_careerinfo" VALUES(294,'sk','Basic Skills','reading work related information',55);
INSERT INTO "career_careerinfo" VALUES(295,'sk','Basic Skills','keeping track of how well people and/or groups are doing in order to make improvements',55);
INSERT INTO "career_careerinfo" VALUES(296,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',55);
INSERT INTO "career_careerinfo" VALUES(297,'sk','Social','changing what is done based on other people''s actions',55);
INSERT INTO "career_careerinfo" VALUES(298,'sk','Social','teaching people how to do something',55);
INSERT INTO "career_careerinfo" VALUES(299,'ab','Verbal','communicate by speaking',55);
INSERT INTO "career_careerinfo" VALUES(300,'ab','Verbal','communicate by writing',55);
INSERT INTO "career_careerinfo" VALUES(301,'ab','Ideas and Logic','notice when problems happen',55);
INSERT INTO "career_careerinfo" VALUES(302,'ab','Ideas and Logic','use rules to solve problems',55);
INSERT INTO "career_careerinfo" VALUES(303,'ps','ps','People interested in this work like activities that include ideas, thinking, and figuring things out.',55);
INSERT INTO "career_careerinfo" VALUES(304,'tech','Analytical or scientific software','Axxya Systems Nutritionist Pro software',55);
INSERT INTO "career_careerinfo" VALUES(305,'tech','Analytical or scientific software','Compu-Cal Nutrition Assistant',55);
INSERT INTO "career_careerinfo" VALUES(306,'tech','Medical software','BioEx Systems Nutrition Maker Plus',55);
INSERT INTO "career_careerinfo" VALUES(307,'tech','Medical software','Lifestyles Technologies DietMaster Pro',55);
INSERT INTO "career_careerinfo" VALUES(308,'tech','Data base user interface and query software','CyberSoft NutriBase software',55);
INSERT INTO "career_careerinfo" VALUES(309,'tech','Data base user interface and query software','Database software',55);
INSERT INTO "career_careerinfo" VALUES(310,'ac','ac','Advertising Director, Advertising Manager, Classified Advertising Manager, Promotions Director',74);
INSERT INTO "career_careerinfo" VALUES(311,'td','td','Plan, direct, or coordinate advertising policies and programs or produce collateral materials, such as posters, contests, coupons, or give-aways, to create extra interest in the purchase of a product or service for a department, an entire organization, or on an account basis.',74);
INSERT INTO "career_careerinfo" VALUES(312,'job','job','Inspect layouts and advertising copy and edit scripts, audio and video tapes, and other promotional material for adherence to specifications.',74);
INSERT INTO "career_careerinfo" VALUES(313,'job','job','Plan and prepare advertising and promotional material to increase sales of products or services, working with customers, company officials, sales departments and advertising agencies.',74);
INSERT INTO "career_careerinfo" VALUES(314,'job','job','Gather and organize information to plan advertising campaigns.',74);
INSERT INTO "career_careerinfo" VALUES(315,'kn','Arts and Humanities','English language',74);
INSERT INTO "career_careerinfo" VALUES(316,'kn','Communications','multimedia',74);
INSERT INTO "career_careerinfo" VALUES(317,'kn','Communications','telecommunications',74);
INSERT INTO "career_careerinfo" VALUES(318,'kn','Business','management',74);
INSERT INTO "career_careerinfo" VALUES(319,'kn','Business','sales and marketing',74);
INSERT INTO "career_careerinfo" VALUES(320,'kn','Engineering and Technology','computers and electronics',74);
INSERT INTO "career_careerinfo" VALUES(321,'sk','Basic Skills','listening to others, not interrupting, and asking good questions',74);
INSERT INTO "career_careerinfo" VALUES(322,'sk','Basic Skills','talking to others',74);
INSERT INTO "career_careerinfo" VALUES(323,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',74);
INSERT INTO "career_careerinfo" VALUES(324,'sk','Social','understanding people''s reactions',74);
INSERT INTO "career_careerinfo" VALUES(325,'sk','Social','changing what is done based on other people''s actions',74);
INSERT INTO "career_careerinfo" VALUES(326,'ab','Verbal','communicate by speaking',74);
INSERT INTO "career_careerinfo" VALUES(327,'ab','Verbal','listen and understand what people say',74);
INSERT INTO "career_careerinfo" VALUES(328,'ab','Ideas and Logic','notice when problems happen',74);
INSERT INTO "career_careerinfo" VALUES(329,'ab','Ideas and Logic','use rules to solve problems',74);
INSERT INTO "career_careerinfo" VALUES(330,'ps','ps','People interested in this work like activities that include leading, making decisions, and business.',74);
INSERT INTO "career_careerinfo" VALUES(331,'tech','Data base user interface and query software','Database software',74);
INSERT INTO "career_careerinfo" VALUES(332,'tech','Data base user interface and query software','Microsoft Marketing Pilot software',74);
INSERT INTO "career_careerinfo" VALUES(333,'tech','Desktop publishing software','Adobe Systems Adobe PageMaker',74);
INSERT INTO "career_careerinfo" VALUES(334,'tech','Desktop publishing software','Quark software',74);
INSERT INTO "career_careerinfo" VALUES(335,'tech','Analytical or scientific software','Business analysis software',74);
INSERT INTO "career_careerinfo" VALUES(336,'tech','Analytical or scientific software','Media Professional software',74);
INSERT INTO "career_careerinfo" VALUES(337,'ac','ac','Audio Engineer, Mixer, Recording Engineer, Sound Engineer',81);
INSERT INTO "career_careerinfo" VALUES(338,'td','td','Operate machines and equipment to record, synchronize, mix, or reproduce music, voices, or sound effects in sporting arenas, theater productions, recording studios, or movie and video productions.',81);
INSERT INTO "career_careerinfo" VALUES(339,'job','job','Confer with producers, performers, and others to determine and achieve the desired sound for a production, such as a musical recording or a film.',81);
INSERT INTO "career_careerinfo" VALUES(340,'job','job','Prepare for recording sessions by performing activities such as selecting and setting up microphones.',81);
INSERT INTO "career_careerinfo" VALUES(341,'job','job','Record speech, music, and other sounds on recording media, using recording equipment.',81);
INSERT INTO "career_careerinfo" VALUES(342,'kn','Engineering and Technology','computers and electronics',81);
INSERT INTO "career_careerinfo" VALUES(343,'kn','Engineering and Technology','product and service development',81);
INSERT INTO "career_careerinfo" VALUES(344,'kn','Communications','multimedia',81);
INSERT INTO "career_careerinfo" VALUES(345,'kn','Communications','telecommunications',81);
INSERT INTO "career_careerinfo" VALUES(346,'kn','Business','customer service',81);
INSERT INTO "career_careerinfo" VALUES(347,'kn','Arts and Humanities','music, dance, visual arts, drama, or sculpture',81);
INSERT INTO "career_careerinfo" VALUES(348,'sk','Basic Skills','listening to others, not interrupting, and asking good questions',81);
INSERT INTO "career_careerinfo" VALUES(349,'sk','Basic Skills','talking to others',81);
INSERT INTO "career_careerinfo" VALUES(350,'sk','Problem Solving','noticing a problem and figuring out the best way to solve it',81);
INSERT INTO "career_careerinfo" VALUES(351,'ab','Verbal','communicate by speaking',81);
INSERT INTO "career_careerinfo" VALUES(352,'ab','Verbal','communicate by writing',81);
INSERT INTO "career_careerinfo" VALUES(353,'ab','Ideas and Logic','order or arrange things',81);
INSERT INTO "career_careerinfo" VALUES(354,'ab','Ideas and Logic','notice when problems happen',81);
INSERT INTO "career_careerinfo" VALUES(355,'ab','Attention','pay attention to something without being distracted',81);
INSERT INTO "career_careerinfo" VALUES(356,'ab','Hearing and Speech','recognize spoken words',81);
INSERT INTO "career_careerinfo" VALUES(357,'ps','ps','People interested in this work like activities that include practical, hands-on problems and solutions.',81);
INSERT INTO "career_careerinfo" VALUES(358,'tech','Music or sound editing software','Avid Digidesign Pro Tools',81);
INSERT INTO "career_careerinfo" VALUES(359,'tech','Music or sound editing software','Avid software',81);
INSERT INTO "career_careerinfo" VALUES(360,'tech','Video creation and editing software
','Apple Final Cut Pro',81);
INSERT INTO "career_careerinfo" VALUES(361,'tech','Data base user interface and query software
','Data entry software',81);
INSERT INTO "career_careerinfo" VALUES(362,'ac','ac',' Archaeologist, Associate Director, Curator, Principal Archaeologist',106);
INSERT INTO "career_careerinfo" VALUES(363,'td','td','Conduct research to reconstruct record of past human life and culture from human remains, artifacts, architectural features, and structures recovered through excavation, underwater recovery, or other means of discovery.',106);
INSERT INTO "career_careerinfo" VALUES(364,'job','job','Study objects and structures recovered by excavation to identify, date, and authenticate them and to interpret their significance.',106);
INSERT INTO "career_careerinfo" VALUES(365,'job','job','Research, survey, or assess sites of past societies and cultures in search of answers to specific research questions.',106);
INSERT INTO "career_careerinfo" VALUES(366,'job','job','Write, present, and publish reports that record site history, methodology, and artifact analysis results, along with recommendations for conserving and interpreting findings.',106);
INSERT INTO "career_careerinfo" VALUES(367,'kn','Arts and Humanities','history and archeology',106);
INSERT INTO "career_careerinfo" VALUES(368,'kn','Arts and Humanities','English language',106);
INSERT INTO "career_careerinfo" VALUES(369,'kn','Math and Science','sociology and anthropology',106);
