INSERT INTO "career_subtag" VALUES(1,'AgriBusiness / Rural',1);
INSERT INTO "career_subtag" VALUES(2,'BioTechnology / Medical MBA',1);
INSERT INTO "career_subtag" VALUES(3,'Entrepreneurship and Family Business',1);
INSERT INTO "career_subtag" VALUES(4,'Executive MBA',1);
INSERT INTO "career_subtag" VALUES(5,'Finance / Investment / Banking',1);
INSERT INTO "career_subtag" VALUES(6,'General Management',1);
INSERT INTO "career_subtag" VALUES(7,'Graduate Courses(BBA / BBM)',1);
INSERT INTO "career_subtag" VALUES(8,'Health Care / Hospital',1);
INSERT INTO "career_subtag" VALUES(9,'Human Resource / Personnel',1);
INSERT INTO "career_subtag" VALUES(10,'Information Technology(IT) / Internet',1);
INSERT INTO "career_subtag" VALUES(11,'Infrastructure / Real Estate',1);
INSERT INTO "career_subtag" VALUES(12,'International Business',1);
INSERT INTO "career_subtag" VALUES(13,'Logistics / Operations / Supply Chain',1);
INSERT INTO "career_subtag" VALUES(14,'Oil / Gas / Energy Management',1);
INSERT INTO "career_subtag" VALUES(15,'Online MBA',1);
INSERT INTO "career_subtag" VALUES(16,'Retail Management',1);
INSERT INTO "career_subtag" VALUES(17,'Sales / marketing / Brand / Advertising',1);
INSERT INTO "career_subtag" VALUES(18,'Aeronautical Engineering',2);
INSERT INTO "career_subtag" VALUES(19,'Aircraft Maintenance Engineering',2);
INSERT INTO "career_subtag" VALUES(20,'Architectural Engineering',2);
INSERT INTO "career_subtag" VALUES(21,'BioTech Engineering',2);
INSERT INTO "career_subtag" VALUES(22,'Chemical Engineering',2);
INSERT INTO "career_subtag" VALUES(23,'Civil Engineering',2);
INSERT INTO "career_subtag" VALUES(24,'Computer Science Engineering',2);
INSERT INTO "career_subtag" VALUES(25,'Electrical and Electronics Engineering',2);
INSERT INTO "career_subtag" VALUES(26,'Electronics and Communication Engineering',2);
INSERT INTO "career_subtag" VALUES(27,'General Engineering',2);
INSERT INTO "career_subtag" VALUES(28,'Industrial Engineering',2);
INSERT INTO "career_subtag" VALUES(29,'Marine Engineering',2);
INSERT INTO "career_subtag" VALUES(30,'Mechanical Engineering',2);
INSERT INTO "career_subtag" VALUES(31,'Technical Engineering Diploma Courses',2);
INSERT INTO "career_subtag" VALUES(32,'Fashion Communication and Design',3);
INSERT INTO "career_subtag" VALUES(33,'Fashion Design',3);
INSERT INTO "career_subtag" VALUES(34,'Fashion Merchandising',3);
INSERT INTO "career_subtag" VALUES(35,'Interior Design',3);
INSERT INTO "career_subtag" VALUES(36,'Jewellery and Accessory Design',3);
INSERT INTO "career_subtag" VALUES(37,'Leather and Footwear',3);
INSERT INTO "career_subtag" VALUES(38,'Textile and Apparel Design',3);
INSERT INTO "career_subtag" VALUES(39,'Animation 2D / 3D',4);
INSERT INTO "career_subtag" VALUES(40,'Game Art and Design',4);
INSERT INTO "career_subtag" VALUES(41,'Graphic Design',4);
INSERT INTO "career_subtag" VALUES(42,'Multimedia',4);
INSERT INTO "career_subtag" VALUES(43,'Web Design and Development',4);
INSERT INTO "career_subtag" VALUES(44,'Airport Operations',5);
INSERT INTO "career_subtag" VALUES(45,'Cabin Crew / Air Hostess Training',5);
INSERT INTO "career_subtag" VALUES(46,'Event Management',5);
INSERT INTO "career_subtag" VALUES(47,'Food Production / Catering',5);
INSERT INTO "career_subtag" VALUES(48,'Hospitality and Tourism Management',5);
INSERT INTO "career_subtag" VALUES(49,'Hotel Management',5);
INSERT INTO "career_subtag" VALUES(50,'Travel and Ticketing',5);
INSERT INTO "career_subtag" VALUES(51,'Ayurveda',6);
INSERT INTO "career_subtag" VALUES(52,'Beauty and Cosmetology',6);
INSERT INTO "career_subtag" VALUES(53,'Clinical Research',6);
INSERT INTO "career_subtag" VALUES(54,'Dental Science',6);
INSERT INTO "career_subtag" VALUES(55,'Dietician and Nutritionist',6);
INSERT INTO "career_subtag" VALUES(56,'Fitness and Health Care',6);
INSERT INTO "career_subtag" VALUES(57,'Homoeopathy',6);
INSERT INTO "career_subtag" VALUES(58,'Medical Science',6);
INSERT INTO "career_subtag" VALUES(59,'Paramedical / Nursing',6);
INSERT INTO "career_subtag" VALUES(60,'Pharmacy',6);
INSERT INTO "career_subtag" VALUES(61,'Physiotherapy',6);
INSERT INTO "career_subtag" VALUES(62,'Veterinary Science',6);
INSERT INTO "career_subtag" VALUES(63,'Accounting',7);
INSERT INTO "career_subtag" VALUES(64,'Banking',7);
INSERT INTO "career_subtag" VALUES(65,'CFP (Certified Financial Planner)',7);
INSERT INTO "career_subtag" VALUES(66,'Chartered Accountancy',7);
INSERT INTO "career_subtag" VALUES(67,'Commerce',7);
INSERT INTO "career_subtag" VALUES(68,'Company Secretary',7);
INSERT INTO "career_subtag" VALUES(69,'Equity / Commodity / Foreign Trade',7);
INSERT INTO "career_subtag" VALUES(70,'Finance',7);
INSERT INTO "career_subtag" VALUES(71,'Insurance / Actuary',7);
INSERT INTO "career_subtag" VALUES(72,'Taxation',7);
INSERT INTO "career_subtag" VALUES(73,'Acting / Modeling',8);
INSERT INTO "career_subtag" VALUES(74,'Advertising & PR',8);
INSERT INTO "career_subtag" VALUES(75,'Anchoring & Jockeying',8);
INSERT INTO "career_subtag" VALUES(76,'Editing',8);
INSERT INTO "career_subtag" VALUES(77,'Film Making & Direction',8);
INSERT INTO "career_subtag" VALUES(78,'Journalism & Mass Comm',8);
INSERT INTO "career_subtag" VALUES(79,'Media Management',8);
INSERT INTO "career_subtag" VALUES(80,'Photography',8);
INSERT INTO "career_subtag" VALUES(81,'Sound Engineering',8);
INSERT INTO "career_subtag" VALUES(82,'Computer Certificate Course',9);
INSERT INTO "career_subtag" VALUES(83,'Hardware / Embedded Systems',9);
INSERT INTO "career_subtag" VALUES(84,'Information & Data Management',9);
INSERT INTO "career_subtag" VALUES(85,'Information Technology',9);
INSERT INTO "career_subtag" VALUES(86,'MCA / BCA',9);
INSERT INTO "career_subtag" VALUES(87,'Networking',9);
INSERT INTO "career_subtag" VALUES(88,'Distance Engineering',10);
INSERT INTO "career_subtag" VALUES(89,'Distance MBA',10);
INSERT INTO "career_subtag" VALUES(90,'Creative Arts',11);
INSERT INTO "career_subtag" VALUES(91,'Languages & Literature',11);
INSERT INTO "career_subtag" VALUES(92,'Performing Arts',11);
INSERT INTO "career_subtag" VALUES(93,'Corporate Law',12);
INSERT INTO "career_subtag" VALUES(94,'Economics',12);
INSERT INTO "career_subtag" VALUES(95,'History',12);
INSERT INTO "career_subtag" VALUES(96,'International Law',12);
INSERT INTO "career_subtag" VALUES(97,'Law',12);
INSERT INTO "career_subtag" VALUES(98,'Philosophy',12);
INSERT INTO "career_subtag" VALUES(99,'Political Science',12);
INSERT INTO "career_subtag" VALUES(100,'Psychology / Sociology',12);
INSERT INTO "career_subtag" VALUES(101,'Public Administration',12);
INSERT INTO "career_subtag" VALUES(102,'Public Policy & Sustainable Development',12);
INSERT INTO "career_subtag" VALUES(103,'Religious Studies',12);
INSERT INTO "career_subtag" VALUES(104,'Societal Development',12);
INSERT INTO "career_subtag" VALUES(105,'Agriculture',13);
INSERT INTO "career_subtag" VALUES(106,'Archaeology',13);
INSERT INTO "career_subtag" VALUES(107,'Astrology',13);
INSERT INTO "career_subtag" VALUES(108,'Environment & Botony',13);
INSERT INTO "career_subtag" VALUES(109,'Food Technology / Processing',13);
INSERT INTO "career_subtag" VALUES(110,'Forensic Science',13);
INSERT INTO "career_subtag" VALUES(111,'Geology',13);
INSERT INTO "career_subtag" VALUES(112,'Horticulture',13);
INSERT INTO "career_subtag" VALUES(113,'Merchant Navy',13);
INSERT INTO "career_subtag" VALUES(114,'Nuclear Science',13);
INSERT INTO "career_subtag" VALUES(115,'Renewable Energy',13);
INSERT INTO "career_subtag" VALUES(116,'Zoology',13);
INSERT INTO "career_subtag" VALUES(117,'Education & Teaching',14);
INSERT INTO "career_subtag" VALUES(118,'Office Administration / Professional Development',14);
INSERT INTO "career_subtag" VALUES(119,'Sports & Athletics',14);
INSERT INTO "career_subtag" VALUES(120,'Vocational Technical Courses',14);
INSERT INTO "career_subtag" VALUES(121,'Armed Forces',15);
INSERT INTO "career_subtag" VALUES(122,'Miscellaneous',15);
