INSERT INTO "career_tag" VALUES(1,'BBA / MBA / Management');
INSERT INTO "career_tag" VALUES(2,'Engineering');
INSERT INTO "career_tag" VALUES(3,'Fashion / Textile Design');
INSERT INTO "career_tag" VALUES(4,'Animation / Multimedia');
INSERT INTO "career_tag" VALUES(5,'Aviation / Travel / Hospitality');
INSERT INTO "career_tag" VALUES(6,'Medicine / Health Care');
INSERT INTO "career_tag" VALUES(7,'Banking / Finance / Accounts');
INSERT INTO "career_tag" VALUES(8,'Media / Films / Journalism');
INSERT INTO "career_tag" VALUES(9,'BCA / MCA / Computers');
INSERT INTO "career_tag" VALUES(10,'Distance Learning / correspondence');
INSERT INTO "career_tag" VALUES(11,'Languages / Arts / Literature');
INSERT INTO "career_tag" VALUES(12,'Politics / Law / Humanities');
INSERT INTO "career_tag" VALUES(13,'Sciences');
INSERT INTO "career_tag" VALUES(14,'Professional / Vocational Courses');
INSERT INTO "career_tag" VALUES(15,'Other');
